version: '3'
services:

  postgres:
    image: postgres:14
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bd
      POSTGRES_DB: estadiauttec
    ports:
      - "5432:5432"
    networks:
      - network-music

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    depends_on:
      - postgres
    networks:
      - network-music

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - "8000:8000"
    volumes:
        - ./:/var/www
        - ./Docker/nginx/:/etc/nginx/conf.d/
    networks:
        - network-music

networks:
  network-music:
    driver: bridge
